# Generated by Django 2.2 on 2019-07-16 17:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('foto', models.ImageField(null=True, upload_to='images/postagens')),
                ('data_post', models.DateTimeField(default=datetime.datetime.now)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='perfis.Perfil')),
            ],
            options={
                'ordering': ['data_post'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('data_comentario', models.DateTimeField(default=datetime.datetime.now)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.Perfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='postagem.Post')),
            ],
            options={
                'ordering': ['data_comentario'],
            },
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reacao', models.CharField(choices=[('gostei', 'Gostei'), ('nao gostei', 'Não gostei')], max_length=10)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.Perfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='postagem.Post')),
            ],
            options={
                'unique_together': {('post', 'perfil')},
            },
        ),
    ]
