# Generated by Django 2.2.2 on 2019-07-14 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('data_post', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='perfis.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reacao', models.CharField(choices=[('gostei', 'Gostei'), ('nao gostei', 'Não gostei')], max_length=10)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.Perfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='postagem.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.Perfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='postagem.Post')),
            ],
        ),
    ]
