# Generated by Django 2.2.2 on 2019-07-14 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['data_comentario']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['data_post']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
