# Generated by Django 2.2 on 2019-07-16 17:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
        ('postagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='perfis_marcados',
            field=models.ManyToManyField(to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='post',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reacao',
            name='data_reacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='perfis.Perfil'),
        ),
        migrations.AlterField(
            model_name='reacao',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='perfis.Perfil'),
        ),
    ]
