# Generated by Django 2.2.2 on 2019-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0004_auto_20190714_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(null=True, upload_to='perfis/static/images/postagens'),
        ),
    ]
