# Generated by Django 2.2.2 on 2019-07-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0005_auto_20190715_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/postagens'),
        ),
    ]
