# Generated by Django 2.2.2 on 2019-07-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0006_auto_20190715_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/postagens'),
        ),
    ]
