# Generated by Django 2.2.3 on 2019-07-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0010_auto_20190625_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bloqueados',
            field=models.ManyToManyField(related_name='_perfil_bloqueados_+', to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(null=True, upload_to='perfis/static/images/foto_perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='convite',
            unique_together={('convidador', 'convidado')},
        ),
    ]
