# Generated by Django 2.2.3 on 2019-07-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0011_auto_20190714_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
